plugins:
  - babel
  - react

extends:
  - airbnb-base
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true

settings:
  react:
    version: "16.12"

rules:
  no-console: 0