plugins:
  - babel
  - react
  - jest

extends:
  - airbnb-base
  - "plugin:react/recommended"
  - 'plugin:jest/recommended'

parser: babel-eslint

env:
  node: true
  jest: true

settings:
  react:
    version: "16.12"

rules:
  no-console: 0
  class-methods-use-this: 0
  react/prop-types: 0
  import/no-unresolved: 0
  import/extensions: 0

globals: {
  "localStorage": true,
  "fetch": true
}
  